name: Tests
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      actions: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        run: npm test
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-results
          path: tests-results.json
        
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests results
          path: tests-results.json
          reporter: mocha-json
          fail-on-error: true